# Generated by Django 3.0.3 on 2022-12-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_parkingspace'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspace',
            old_name='serialNo',
            new_name='spaceCol',
        ),
        migrations.AddField(
            model_name='parkingspace',
            name='spaceRow',
            field=models.CharField(default=None, max_length=2),
        ),
    ]
