# Generated by Django 3.0.3 on 2022-12-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20221206_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='spaceCol',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='spaceRow',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
