# Generated by Django 3.0.3 on 2022-12-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20221206_1140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
